### PR TITLE
Fix missing import.

### PR DESCRIPTION
**Pull request by bastump**

### CODE REVIEW

**Review by bastump — COMMENTED** [review]
This is a one liner missing import.

**Review by ghost — APPROVED** [review]

**Comment by MateusAmin** [comment]
@samanoAre we not compile checking the scripts in the zip folder?

**Review by MateusAmin — COMMENTED** [review]
LGTM

**Comment by nhmathis** [comment]
@MateusAmin We can't since we need access to the IIB jars. This is done in the Ant builds, but not gradle. The IIB jars are not publicly available. This should be happening in other projects.

**Pull request merged**
